### ISSUE TITLE
Accessing fields other than title, body and data from RemoteMessage could be improved.

### ISSUE THREAD

**Issue by eric-labelle** [Azure/azure-notificationhubs-android#139]
Hey guys! Looking at the built-in `FirebaseReceiver` in version `1.1.1`, I was wondering why are you stripping everything except the `title`, `body` and `data` from the incoming `RemoteMessage` in order to return a `BasicNotificationMessage`? 

> https://github.com/Azure/azure-notificationhubs-android/blob/e0cff63f34ec943db1bd7d81a5c278c502e491bc/notification-hubs-sdk/src/main/java/com/microsoft/windowsazure/messaging/notificationhubs/FirebaseReceiver.java#L91

What would be the recommended approach to use all the other fields from a RemoteMessage (`channelId`, `imageUrl`, `icon`, `sound` etc..) ?

To make it much more flexible, it would be useful to be able to override the `getNotificationMessage(): BasicNotificationMessage` and change it's return type to the interface NotificationMessage in order to be able to extend it.

* Currently, the only option I found is to copy the whole `FirebaseReceiver` in the same package (_because many methods are package-private_) and redefine this new custom FirebaseReceiver in our manifest to be able to control what is returned when a new message is received. 
* Another option would be to use a fully custom payload with all those fields in the `data` map but that's not really practical and won't respect the standard [JSON Schema](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification).

Thanks

**Comment by mpodwysocki** [comment]
@eric-labelle Using the `getData()` method, you can get anything that you want from the message itself that we do not directly expose. For example, if you want to get the badge, you can do the following:

```java
String badge = message.getData().get("badge");
```

Are there any fields in particular you feel should be at the top level?

**Comment by eric-labelle** [comment]
Yes but that implies that we need to put everything in the data map in the payload, all the fields defined in there https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification

The fields for android notification are in a notification node in the payload, but these are all stripped out by the ANH FirebaseReceiver, except `title` and `body`

Using this payload, I would never be able to get the channelId and image except if I redefine a custom FirebaseReceiver and change the method `getNotificationMessage` to return an implementation of `NotificationMessage` (from ANH) which would contain all fields from `RemoteMessage` (from FCM).
```
{
  "notification": {
    "title": "ANH TITLE",
    "body": "ANH BODY",
    "image": "imageUrlInNotification"
    "channelId": "ANH_TEST_CHANNEL"
  },
  "data": {
    "message": "Notification Hub test notification",
    "imageInData": "myImageUrl"
  }
}
```

**Comment by marstr** [comment]
Howdy @eric-labelle,

This is good feedback, and exactly the sort of thing that we want to hear so that we can prioritize work moving forward.

This decision was made in order to keep some healthy separation in our API from Firebase. For example, Amazon Device Messaging (ADM) and Baidu are both Android based and use the Intent system with a different set of properties when delivering notifications. We want to keep our API flexible enough to allow supporting these other push providers in the future, and the way that made most sense for our initial release was to keep the message agnostic with a limited set of properties. There are other options, and we'll make sure to take your voice into consideration as we continue to develop this SDK.

For the moment, I think your work-around of effectively vendoring our `FirebaseReceiver` implementation and overriding the manifest makes a lot of sense. I know it's a hassle, but I'm glad you found something that works.

**Comment by eric-labelle** [comment]
Sounds good. Thanks for your time and for explaining the reasoning behind. Looking forward for a more flexible system in the future releases then. Perhaps it will be available when and if we decide to go forward with ANH. I was just looking at the capabilities and functionalities it offers.

**Comment by eric-labelle** [comment]
Actually, reading through [FCM documentation](https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages), my option 2 (_using the data node for everything_) isn't even possible because the `data` node is not delivered while in background until the app is opened only the `notification` node is available. 
So it makes it impossible for me to prevent the user from receiving a notification in a channel he disabled since the `channel_id` won't  be there. Not sure how to handle Android channels with ANH, at first I though about registering a tag for every channel but then since this setting is in the Android System preference, if the user disable a channel, the user needs to go back in our app so we can detect the channel has been disabled and then remove this tag subscription from ANH which is pretty error-prone. :(

**Comment by marstr** [comment]
Howdy @eric-labelle, we've been doing a little more thinking about this issue. One of the things we've discussed is shipping separate `.aar`s for each Push Notification Service (PNS). This will allow us to keep the transitive dependency weight of our library to a minimum for everyone, while supporting push services other than Firebase Cloud Messaging on devices where it isn't available.

Given that we're thinking of having a product flavor and source set per PNS, one option would be to ship different definitions of `NotificationListener`. Doing this would allow us to pass a Firebase `RemoteMessage` to listeners directly, instead of wrapping it in our own type. An obvious downside is that this exposes us to breaking changes in the FCM library, but in our circumstances that may not be as dire as it would be in a more general purpose SDK.

As an Android developer, and someone interested in ANH, would you appreciate this approach? Or would you prefer that this SDK continue to abstract over the details of the PNS?

**Comment by eric-labelle** [comment]
Hi! So basically we'd have 2 dependencies with this approach? The last one being only the custom listener for each implementation (fcm, kindle etc.) Sound decent to me and should provide enough flexibility to anyone while having access to the whole RemoteMessage payload! :)
`
implementation("com.microsoft.azure:notification-hubs-android-sdk:1.1.2")
implementation("com.microsoft.azure:notification-hubs-android-sdk-fcm:1.1.2")
`

Correct me if I got that wrong but it would be something like
```
// in MainActivity
NotificationHub.setListener(CustomNotificationListener())

// class CustomNotificationListener
class CustomNotificationListener : FCMNotificationListener {
    override fun onPushNotificationReceived(context: Context, remoteMessage: RemoteMessage) {
          ....
    }
}
```
Thanks

**Comment by marstr** [comment]
You're pretty darn close to what we were thinking! What I was talking about would have just one dependency: `implementation("com.microsoft.azure:-notification-hubs-android-sdk-fcm:1.1.2")`. We think this approach would be simpler for customers - because we don't think there will be devices that simultaneously need to listen for FCM and ADM messages. @zhangeugenia and I threw together a PR over here with an example of what our sample application would look like if we were to adopt this strategy: #150

**Comment by marstr** [comment]
Hey @eric-labelle, there's a new SKU of the SDK available now that uses `RemoteMessage` directly.

Just swap out your dependency line from:
``` Groovy
implementation 'com.microsoft.azure:notification-hubs-android-sdk:1.1.3'
```
to
``` Groovy
implementation 'com.microsoft.azure:notification-hubs-android-sdk-fcm:1.1.3'
```

> Note: these are two alternate downloads and will not work together.

**Comment by marstr** [comment]
Doing some house-keeping. This item was fixed by publishing an alternate SKU starting with version `1.1.3`. Closing as resolved.
